# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1942e5783b66076ee30f65a878168ffa3d5a9b23c3a94e45c4535702d3a1cd82180e186fe347439d6b4d69be19ddc29954db159135de8d7af6302064a6e1ab65

test:
  secret_key_base: 264bcb13ece596f2d89bebd4529f70545214c02908a3f477cec8fabd09dc6a6971b083783604f1d9440fff7bf4a7152dcc1113ba860ff4361180292fe657f051

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
